add landing
minimal-dev/aqua-protocol pull request #1
Opened 2021-01-27 12:34 UTC by animetalist

2021-01-27 12:35 UTC, minimal-dev commented
Task linked: [CU-cuwakp Coding Aqua Protocol landing page](https://app.clickup.com/t/cuwakp)

2021-01-27 21:02 UTC, salexpro requested changes

2021-01-28 16:56 UTC, salexpro approved these changes

2021-01-28 17:04 UTC, salexpro approved these changes

2021-01-28 17:04 UTC, merged