tarafixes
minimal-dev/aqua-protocol pull request #2
Opened 2021-02-01 16:54 UTC by animetalist

2021-02-01 16:54 UTC, minimal-dev commented
Task linked: [CU-cuwakp Coding Aqua Protocol landing page](https://app.clickup.com/t/cuwakp)

2021-02-01 19:18 UTC, salexpro requested changes

2021-02-01 19:18 UTC, salexpro commented on src/js/app.js
> +});
это зачем, на шо scrolled класс вообще влияет

2021-02-01 19:18 UTC, salexpro commented on src/scss/components/_menu.scss
> +    &:hover {
ховеры есть, фокусов нет

2021-02-01 19:18 UTC, salexpro commented on src/scss/sections/_header.scss
> +  .is-open-top &::before {
опять твои стремные конструкции без иерархии

2021-02-07 18:57 UTC, salexpro requested changes

2021-02-07 18:57 UTC, salexpro commented on src/scss/sections/_header.scss
> +      transition: all 300ms ease-in;
если на то пошло то у тебя наоборот местами должны быт ease-in и ease-out, проще просто оставить ease-out

2021-02-09 10:54 UTC, salexpro approved these changes

2021-02-09 10:54 UTC, merged